# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(371, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setEnabled(True)
        self.btn_start.setGeometry(QtCore.QRect(30, 70, 311, 71))
        self.btn_start.setObjectName("btn_start")
        self.btn_con = QtWidgets.QPushButton(self.centralwidget)
        self.btn_con.setGeometry(QtCore.QRect(30, 160, 311, 71))
        self.btn_con.setObjectName("btn_con")
        self.btn_dcon = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dcon.setGeometry(QtCore.QRect(30, 250, 311, 71))
        self.btn_dcon.setObjectName("btn_dcon")
        self.con_msg = QtWidgets.QLabel(self.centralwidget)
        self.con_msg.setEnabled(True)
        self.con_msg.setGeometry(QtCore.QRect(30, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.con_msg.setFont(font)
        self.con_msg.setText("")
        self.con_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.con_msg.setObjectName("con_msg")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KESKIFE"))
        self.btn_start.setText(_translate("MainWindow", "Запустить сервер"))
        self.btn_con.setText(_translate("MainWindow", "Подключиться"))
        self.btn_dcon.setText(_translate("MainWindow", "Отключиться"))
